### ISSUE TITLE
Develop API endpoints to restore deleted vendor accounts

### ISSUE THREAD

**Issue by Freeman-kuch** [hngx-org/spitfire-super-admin-one#12]
**Develop API endpoints to restore deleted accounts. Ensure that the account restrictions are removed completely, and users will be able to view the vendor's shop.**

**Comment by samuelogboye** [comment]
I was assigned this. I'll be working on it

**Comment by Freeman-kuch** [comment]
> I was assigned this. I'll be working on it

assigned the task to you

**Comment by samuelogboye** [comment]
> > I was assigned this. I'll be working on it
> 
> assigned the task to you

Thanks chief.

**Comment by samuelogboye** [comment]
Please revoke my assignment for this. I just checked my linear for the right one..![image](https://github.com/hngx-org/spitfire-super-admin-one/assets/125566090/37c2101e-dd7a-406e-99ac-091b04ae0786)

**Comment by Murad039** [comment]
its actually assigned to me

**Comment by Murad039** [comment]
but samuel i might need to do some pair programming we can work together if u have enough time
