### ISSUE TITLE
Develop API endpoints to restore deleted product listings

### ISSUE THREAD

**Issue by Freeman-kuch** [hngx-org/spitfire-super-admin-one#13]
**Develop API endpoints to restore deleted products. The product will be pushed back to its initial state before deletion.**

**Comment by samuelogboye** [comment]
Apologies this is the one for me. It was a mistake.

**Comment by samuelogboye** [comment]
![image](https://github.com/hngx-org/spitfire-super-admin-one/assets/125566090/84b9541d-9715-4a6e-b451-107e2fc995bd)
