### ISSUE TITLE
Document all endpoints created by the BE

### ISSUE THREAD

**Issue by Freeman-kuch** [hngx-org/spitfire-super-admin-one#26]
**Create API documentation for Super Admin API: Using tools like Swagger/OpenAPI, Postman create a well detailed Documentation on all endpoints in the team project.This documentation outlines essential tasks that super admins can perform, including retrieving vendors information, updating profiles, deleting and restoring vendors profile, Banning and unbanning, deleting and restoring products.**

**Comment by Zainabfadeyi** [comment]
assign me 
my boss
