### ISSUE TITLE
Develop API endpoints to permanently delete product listings

### ISSUE THREAD

**Issue by Freeman-kuch** [hngx-org/spitfire-super-admin-one#4]
**Develop API endpoint to permanently delete product listing. Permanently deleted products will be deleted completely from the platform. This action is an irreversible one. However, there are loggings to show deleted products history.**

**Comment by DestinedCodes** [comment]
On it boss.

**Comment by Freeman-kuch** [comment]
We need to discuss on how this will fit out schema @DestinedCodes
